# Generated by Django 4.2.30 on 2026-05-09 13:38

import apps.products.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalProduct",
            fields=[
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("slug", models.SlugField(max_length=140, verbose_name="slug")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="description"),
                ),
                ("price_cents", models.PositiveIntegerField(verbose_name="price (cents)")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="stock quantity"),
                ),
                (
                    "image",
                    models.TextField(blank=True, max_length=100, null=True, verbose_name="image"),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="is active"),
                ),
                ("history_user_id", models.UUIDField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical product",
                "verbose_name_plural": "historical products",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("slug", models.SlugField(max_length=140, unique=True, verbose_name="slug")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="description"),
                ),
                ("price_cents", models.PositiveIntegerField(verbose_name="price (cents)")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="stock quantity"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.products.models.product_image_upload_path,
                        verbose_name="image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="is active"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "products_product",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "-created_at"], name="products_pr_is_acti_645007_idx"
                    )
                ],
            },
        ),
    ]
