# Generated by Django 4.2.30 on 2026-05-02 11:27

import apps.orders.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("placed", "Placed"),
                            ("paid", "Paid"),
                            ("in_production", "In production"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vinilo_blanco", "Vinilo blanco"),
                            ("vinilo_transparente", "Vinilo transparente"),
                            ("holografico", "Holográfico"),
                            ("luminiscente", "Luminiscente"),
                            ("holografico_transparente", "Holográfico transparente"),
                            ("plateado", "Plateado"),
                            ("dorado", "Dorado"),
                            ("eggshell", "Eggshell"),
                            ("eggshell_holografico", "Eggshell holográfico"),
                        ],
                        default="",
                        max_length=32,
                        verbose_name="material",
                    ),
                ),
                ("width_mm", models.PositiveIntegerField(default=0, verbose_name="width (mm)")),
                ("height_mm", models.PositiveIntegerField(default=0, verbose_name="height (mm)")),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "with_design_service",
                    models.BooleanField(default=False, verbose_name="with design service"),
                ),
                ("with_varnish", models.BooleanField(default=False, verbose_name="with varnish")),
                ("with_relief", models.BooleanField(default=False, verbose_name="with relief")),
                (
                    "relief_note",
                    models.TextField(blank=True, default="", verbose_name="relief note"),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="recipient name"
                    ),
                ),
                (
                    "street_line_1",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="street line 1"
                    ),
                ),
                (
                    "street_line_2",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="street line 2"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, default="", max_length=120, verbose_name="city"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, default="", max_length=2, verbose_name="country"),
                ),
                (
                    "total_amount_cents",
                    models.PositiveIntegerField(default=0, verbose_name="total (cents)"),
                ),
                (
                    "currency",
                    models.CharField(default="EUR", max_length=3, verbose_name="currency"),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=255,
                        verbose_name="stripe payment intent id",
                    ),
                ),
                (
                    "placed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="placed at"),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="paid at")),
                (
                    "shipped_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="shipped at"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="delivered at"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="cancelled at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "orders_order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalOrder",
            fields=[
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("placed", "Placed"),
                            ("paid", "Paid"),
                            ("in_production", "In production"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vinilo_blanco", "Vinilo blanco"),
                            ("vinilo_transparente", "Vinilo transparente"),
                            ("holografico", "Holográfico"),
                            ("luminiscente", "Luminiscente"),
                            ("holografico_transparente", "Holográfico transparente"),
                            ("plateado", "Plateado"),
                            ("dorado", "Dorado"),
                            ("eggshell", "Eggshell"),
                            ("eggshell_holografico", "Eggshell holográfico"),
                        ],
                        default="",
                        max_length=32,
                        verbose_name="material",
                    ),
                ),
                ("width_mm", models.PositiveIntegerField(default=0, verbose_name="width (mm)")),
                ("height_mm", models.PositiveIntegerField(default=0, verbose_name="height (mm)")),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "with_design_service",
                    models.BooleanField(default=False, verbose_name="with design service"),
                ),
                ("with_varnish", models.BooleanField(default=False, verbose_name="with varnish")),
                ("with_relief", models.BooleanField(default=False, verbose_name="with relief")),
                (
                    "relief_note",
                    models.TextField(blank=True, default="", verbose_name="relief note"),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="recipient name"
                    ),
                ),
                (
                    "street_line_1",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="street line 1"
                    ),
                ),
                (
                    "street_line_2",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="street line 2"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, default="", max_length=120, verbose_name="city"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, default="", max_length=2, verbose_name="country"),
                ),
                (
                    "total_amount_cents",
                    models.PositiveIntegerField(default=0, verbose_name="total (cents)"),
                ),
                (
                    "currency",
                    models.CharField(default="EUR", max_length=3, verbose_name="currency"),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=255,
                        verbose_name="stripe payment intent id",
                    ),
                ),
                (
                    "placed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="placed at"),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="paid at")),
                (
                    "shipped_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="shipped at"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="delivered at"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="cancelled at"),
                ),
                ("history_user_id", models.UUIDField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical order",
                "verbose_name_plural": "historical orders",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OrderFile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("original", "Original"), ("die_cut_mask", "Die-cut mask")],
                        max_length=20,
                        verbose_name="kind",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.orders.models.order_file_upload_path, verbose_name="file"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="mime type"
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(default=0, verbose_name="size (bytes)"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "orders_orderfile",
                "ordering": ["-created_at"],
                "unique_together": {("order", "kind")},
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "-created_at"], name="orders_orde_status_079368_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created_by", "-created_at"], name="orders_orde_created_f3f9c3_idx"
            ),
        ),
    ]
