# Generated by Django 4.2.30 on 2026-05-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_historicalorder_quantity_alter_order_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="shape",
            field=models.CharField(
                choices=[
                    ("contorneado", "Corte contorneado"),
                    ("cuadrado", "Cuadrado"),
                    ("circulo", "Círculo"),
                    ("redondeadas", "Esquinas redondeadas"),
                ],
                default="contorneado",
                max_length=20,
                verbose_name="shape",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shape",
            field=models.CharField(
                choices=[
                    ("contorneado", "Corte contorneado"),
                    ("cuadrado", "Cuadrado"),
                    ("circulo", "Círculo"),
                    ("redondeadas", "Esquinas redondeadas"),
                ],
                default="contorneado",
                max_length=20,
                verbose_name="shape",
            ),
        ),
    ]
