# Generated by Django 4.2.30 on 2026-05-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_historicalorder_shape_order_shape"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderfile",
            name="kind",
            field=models.CharField(
                choices=[
                    ("original", "Original"),
                    ("die_cut_mask", "Die-cut mask"),
                    ("cut_path", "Cut path"),
                ],
                max_length=20,
                verbose_name="kind",
            ),
        ),
    ]
