# Generated by Django 4.2.30 on 2026-05-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_orderfile_kind"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalorder",
            name="with_design_service",
        ),
        migrations.RemoveField(
            model_name="historicalorder",
            name="with_varnish",
        ),
        migrations.RemoveField(
            model_name="order",
            name="with_design_service",
        ),
        migrations.RemoveField(
            model_name="order",
            name="with_varnish",
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="with_barniz_brillo",
            field=models.BooleanField(default=False, verbose_name="with gloss varnish"),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="with_barniz_opaco",
            field=models.BooleanField(default=False, verbose_name="with matte varnish"),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="with_tinta_blanca",
            field=models.BooleanField(default=False, verbose_name="with white ink"),
        ),
        migrations.AddField(
            model_name="order",
            name="with_barniz_brillo",
            field=models.BooleanField(default=False, verbose_name="with gloss varnish"),
        ),
        migrations.AddField(
            model_name="order",
            name="with_barniz_opaco",
            field=models.BooleanField(default=False, verbose_name="with matte varnish"),
        ),
        migrations.AddField(
            model_name="order",
            name="with_tinta_blanca",
            field=models.BooleanField(default=False, verbose_name="with white ink"),
        ),
    ]
