# Generated by Django 4.2.30 on 2026-05-09 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("orders", "0005_repricing_addons"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="kind",
            field=models.CharField(
                choices=[("sticker", "Sticker (custom)"), ("catalog", "Catalog product")],
                db_index=True,
                default="sticker",
                max_length=16,
                verbose_name="kind",
            ),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="products.product",
                verbose_name="product",
            ),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="product_quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="product quantity"),
        ),
        migrations.AddField(
            model_name="order",
            name="kind",
            field=models.CharField(
                choices=[("sticker", "Sticker (custom)"), ("catalog", "Catalog product")],
                db_index=True,
                default="sticker",
                max_length=16,
                verbose_name="kind",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="products.product",
                verbose_name="product",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="product_quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="product quantity"),
        ),
    ]
