# Generated by Django 4.2.30 on 2026-05-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_kind_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderfile",
            name="kind",
            field=models.CharField(
                choices=[
                    ("original", "Original"),
                    ("die_cut_mask", "Die-cut mask"),
                    ("cut_path", "Cut path"),
                    ("preview_composite", "Preview composite"),
                ],
                max_length=20,
                verbose_name="kind",
            ),
        ),
    ]
