# Generated by Django 4.2.30 on 2026-05-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_orderfile_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="shipping_method",
            field=models.CharField(
                choices=[
                    ("normal", "Envío normal (7-10 días)"),
                    ("express", "Envío express (2-3 días)"),
                    ("flash", "Envío flash (1 día)"),
                ],
                default="normal",
                max_length=10,
                verbose_name="shipping method",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method",
            field=models.CharField(
                choices=[
                    ("normal", "Envío normal (7-10 días)"),
                    ("express", "Envío express (2-3 días)"),
                    ("flash", "Envío flash (1 día)"),
                ],
                default="normal",
                max_length=10,
                verbose_name="shipping method",
            ),
        ),
    ]
