# Generated by Django 4.2.30 on 2026-05-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_historicalorder_shipping_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="shipping_email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="shipping email"
            ),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="shipping_phone",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="shipping phone"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="shipping email"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_phone",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="shipping phone"
            ),
        ),
    ]
