# Generated by Django 4.2.30 on 2026-05-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_historicalorder_shipping_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="shipping_carrier",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="shipping carrier"
            ),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="shipping_eta_date",
            field=models.DateField(blank=True, null=True, verbose_name="shipping ETA date"),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="shipping_tracking_code",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="shipping tracking code"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_carrier",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="shipping carrier"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_eta_date",
            field=models.DateField(blank=True, null=True, verbose_name="shipping ETA date"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_tracking_code",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="shipping tracking code"
            ),
        ),
    ]
