# Generated by Django 4.2.30 on 2026-05-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_historicalorder_shipping_carrier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="pickup_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="pickup at"),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="reserved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="reserved at"),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="pickup at"),
        ),
        migrations.AddField(
            model_name="order",
            name="reserved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="reserved at"),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("placed", "Placed"),
                    ("reserved", "Reserved for pickup"),
                    ("paid", "Paid"),
                    ("in_production", "In production"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("placed", "Placed"),
                    ("reserved", "Reserved for pickup"),
                    ("paid", "Paid"),
                    ("in_production", "In production"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
