# Generated by Django 4.2.30 on 2026-05-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_historicalorder_pickup_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorder",
            name="shape",
            field=models.CharField(
                choices=[
                    ("contorneado", "Corte contorneado"),
                    ("cuadrado", "Cuadrado"),
                    ("circulo", "Círculo"),
                    ("redondeadas", "Esquinas redondeadas"),
                    ("oval", "Óvalo"),
                ],
                default="contorneado",
                max_length=20,
                verbose_name="shape",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shape",
            field=models.CharField(
                choices=[
                    ("contorneado", "Corte contorneado"),
                    ("cuadrado", "Cuadrado"),
                    ("circulo", "Círculo"),
                    ("redondeadas", "Esquinas redondeadas"),
                    ("oval", "Óvalo"),
                ],
                default="contorneado",
                max_length=20,
                verbose_name="shape",
            ),
        ),
    ]
