# Generated by Django 4.2.30 on 2026-05-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_alter_historicalorder_shape_alter_order_shape"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="discount_cents",
            field=models.PositiveIntegerField(default=0, verbose_name="discount (cents, pre-IVA)"),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="discount_code",
            field=models.CharField(
                blank=True, default="", max_length=40, verbose_name="discount code"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_cents",
            field=models.PositiveIntegerField(default=0, verbose_name="discount (cents, pre-IVA)"),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_code",
            field=models.CharField(
                blank=True, default="", max_length=40, verbose_name="discount code"
            ),
        ),
    ]
