"""
Cut-path SVG generation.

For each paid order, the printer needs a vector file describing the cutter
path at the customer's chosen physical size. We emit SVG because:

  - Universal — every modern cutter / Illustrator / Inkscape opens it.
  - Vector — no resolution loss when the printer scales it.
  - Plain text — easy to inspect / diff / commit / tweak by hand.

Coordinate system:
  The SVG uses millimeters as the user unit (`width="50mm" height="50mm"`
  with viewBox in the same units). Cutters interpret 1 SVG user unit = 1mm
  when the SVG declares physical dimensions. A 50×50 mm sticker emits a
  50×50 viewBox.

Per-shape behavior:

  contorneado:
    The customer's `die_cut_mask` PNG (a black silhouette on transparent
    background, generated by the editor's auto-cut + dilate pipeline)
    is the ground truth. We trace its alpha contour and emit the
    polygon as `<path d="...">` at the customer's chosen size.
    If no mask file exists (customer skipped Auto cut), we fall back
    to a rectangle at width × height, same as `cuadrado`.

  cuadrado:
    `<rect width=W height=H>` — straightforward.

  circulo:
    `<ellipse cx=W/2 cy=H/2 rx=W/2 ry=H/2>` — handles rectangular
    "circles" too if the customer picked unequal width/height.

  redondeadas:
    `<rect rx=r ry=r>` where `r` is 10% of the shorter edge (matches
    the editor's preview).

The SVG is saved as an OrderFile(kind='cut_path') and downloadable
from Django admin or the API.
"""

from __future__ import annotations

import io
import logging
from typing import Iterable

from PIL import Image
from django.core.files.base import ContentFile

logger = logging.getLogger(__name__)

# Small numerical guard: when tracing the alpha contour we emit one polygon
# per "outer" ring. Skip rings smaller than this fraction of total area.
_MIN_CONTOUR_FRACTION = 0.005


def _alpha_to_path(mask_pil: Image.Image, width_mm: int, height_mm: int) -> str | None:
    """Trace the alpha channel of a PNG mask into an SVG path.

    The mask is a binary silhouette: pixels with alpha > 128 are "inside the
    cut", everything else is "outside". We walk the boundary using a simple
    marching-squares-style scan, then map the pixel coordinates to mm via
    the customer's chosen physical dimensions.

    Returns an SVG `d` attribute value, or None if the mask is empty / has
    no usable contour.
    """
    if mask_pil.mode != "RGBA":
        mask_pil = mask_pil.convert("RGBA")

    px_w, px_h = mask_pil.size
    if px_w == 0 or px_h == 0:
        return None

    # Build a binary alpha grid (1 = inside).
    alpha = mask_pil.split()[3]
    binary = alpha.point(lambda v: 255 if v > 128 else 0)
    px = binary.load()

    # Quick bbox check — skip empty masks.
    bbox = binary.getbbox()
    if bbox is None:
        return None

    # Trace the OUTER boundary using a flood-fill-from-the-outside trick:
    # any pixel reachable from the canvas border by walking through "outside"
    # pixels is "outside"; the rest is "inside". The outer boundary is the
    # set of inside pixels adjacent to outside pixels. We then walk that
    # boundary in order using Moore-neighbor tracing.
    #
    # OpenCV would give us this in one call (cv.findContours), but we don't
    # want to add a heavyweight dep just for this — Pillow + a small custom
    # tracer is enough for the relatively simple shapes the editor produces
    # (one outer contour per sticker, after the dilate step).

    inside_at = lambda x, y: 0 <= x < px_w and 0 <= y < px_h and px[x, y] > 0  # noqa: E731

    # Find a starting boundary pixel: scan top-left to bottom-right, take
    # the first inside pixel.
    start = None
    for y in range(px_h):
        for x in range(px_w):
            if inside_at(x, y):
                start = (x, y)
                break
        if start is not None:
            break
    if start is None:
        return None

    # Moore-neighbor tracing — 8-connected. Directions: 0=E, 1=SE, 2=S,
    # 3=SW, 4=W, 5=NW, 6=N, 7=NE.
    directions = [
        (1, 0), (1, 1), (0, 1), (-1, 1),
        (-1, 0), (-1, -1), (0, -1), (1, -1),
    ]
    boundary: list[tuple[int, int]] = [start]
    cur = start
    # Initial backtrack direction: we entered from "outside" on the left
    # (pixel to the left of `start` is outside by construction since `start`
    # is the first inside pixel scanning row-major).
    backtrack_dir = 4  # West
    max_steps = px_w * px_h * 4  # safety upper bound; well above any real shape

    for _ in range(max_steps):
        # Search clockwise starting from the position one CCW from backtrack
        # ((backtrack + 1) mod 8 in our direction list, which is laid out
        # clockwise starting at East).
        found = False
        for i in range(1, 9):
            d = (backtrack_dir + i) % 8
            dx, dy = directions[d]
            nx, ny = cur[0] + dx, cur[1] + dy
            if inside_at(nx, ny):
                # The previous (i-1) direction is the new backtrack — that's
                # where we came from relative to the new pixel.
                backtrack_dir = (d + 4) % 8
                cur = (nx, ny)
                boundary.append(cur)
                found = True
                break
        if not found:
            # Isolated pixel — emit a tiny dot (rare; binary mask thresholds
            # should have removed speckle by now).
            break
        # Standard termination: back to start AND came in from the same
        # direction we left it.
        if cur == start and len(boundary) > 2:
            boundary.pop()  # drop the duplicate
            break

    if len(boundary) < 3:
        return None

    # Simplify the polygon — Moore tracing emits one point per pixel which
    # is too dense for an SVG. Subsample to one point every ~N pixels along
    # the boundary; the cutter will smooth the rest. Picks N to target ~200
    # boundary points regardless of input size.
    target_points = 200
    step = max(1, len(boundary) // target_points)
    sampled = boundary[::step]
    if sampled[-1] != boundary[-1]:
        sampled.append(boundary[-1])

    # Map pixel coords → mm. Pixel (0,0) is top-left → SVG (0,0) top-left
    # (same convention).
    sx = width_mm / px_w
    sy = height_mm / px_h

    parts: list[str] = []
    for i, (x, y) in enumerate(sampled):
        cmd = "M" if i == 0 else "L"
        parts.append(f"{cmd}{x * sx:.3f},{y * sy:.3f}")
    parts.append("Z")
    return " ".join(parts)


def _wrap_svg(width_mm: int, height_mm: int, body: str) -> str:
    """Wrap a path/rect/etc. body in a complete, cutter-friendly SVG document.

    Stroke conventions:
      - 1 cut line, no fill — that's what the cutter follows.
      - `stroke="red"` is the de-facto standard for "cut here" across most
        cutting software (Roland, GCC, Cricut, Silhouette).
      - `stroke-width="0.1mm"` — hair-thin so the cutter's path planner
        treats it as a centerline, not a stroked rectangle.
    """
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n'
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'width="{width_mm}mm" height="{height_mm}mm" '
        f'viewBox="0 0 {width_mm} {height_mm}">\n'
        '  <g fill="none" stroke="red" stroke-width="0.1">\n'
        f'    {body}\n'
        '  </g>\n'
        '</svg>\n'
    )


def build_cut_svg(
    *,
    shape: str,
    width_mm: int,
    height_mm: int,
    mask_file=None,
) -> str:
    """Generate the SVG cut-path string for an order.

    For `contorneado` we trace the customer's `mask_file` (an OrderFile
    holding the PNG die-cut mask). For the geometric shapes we emit
    primitives sized to width × height. If the mask file is missing for
    contorneado we degrade gracefully to a rectangle — the customer can
    still get a printed sticker, just without the auto-detected outline.
    """
    if shape == "contorneado" and mask_file is not None:
        try:
            with mask_file.open("rb") as f:
                pil = Image.open(f)
                pil.load()  # force read while the file is open
            d = _alpha_to_path(pil, width_mm, height_mm)
            if d:
                return _wrap_svg(width_mm, height_mm, f'<path d="{d}" />')
        except Exception as exc:
            logger.warning(
                "Failed to trace die_cut_mask for contorneado order; "
                "falling back to rectangle. error=%s",
                exc,
            )

    # Geometric shapes (or contorneado fallback).
    if shape == "circulo":
        rx = width_mm / 2
        ry = height_mm / 2
        body = f'<ellipse cx="{rx}" cy="{ry}" rx="{rx}" ry="{ry}" />'
    elif shape == "redondeadas":
        # Corner radius = 10% of the shorter edge — matches the editor's
        # preview (geometricMaskPoints in EditorView).
        r = round(min(width_mm, height_mm) * 0.1, 3)
        body = (
            f'<rect x="0" y="0" '
            f'width="{width_mm}" height="{height_mm}" '
            f'rx="{r}" ry="{r}" />'
        )
    else:
        # cuadrado OR contorneado-without-mask fallback.
        body = (
            f'<rect x="0" y="0" '
            f'width="{width_mm}" height="{height_mm}" />'
        )

    return _wrap_svg(width_mm, height_mm, body)


def generate_cut_path_file(order) -> "OrderFile":
    """Build the cut-path SVG for the order and persist it as an OrderFile.

    Idempotent: if a cut_path file already exists for the order it is
    replaced (the unique_together(order, kind) constraint enforces one
    per order). Returns the OrderFile.
    """
    from .models import OrderFile  # avoid circular import

    mask_file = None
    mask_qs = order.files.filter(kind="die_cut_mask")
    if mask_qs.exists():
        mask_file = mask_qs.first().file

    svg = build_cut_svg(
        shape=order.shape,
        width_mm=order.width_mm,
        height_mm=order.height_mm,
        mask_file=mask_file,
    )

    # Replace any existing cut_path file (unique_together would reject
    # otherwise). Saves us a migration that drops the constraint.
    OrderFile.objects.filter(order=order, kind="cut_path").delete()

    name = f"order_{order.uuid}_cut.svg"
    f = OrderFile(order=order, kind="cut_path")
    f.file.save(name, ContentFile(svg.encode("utf-8")), save=False)
    f.mime_type = "image/svg+xml"
    f.size_bytes = len(svg.encode("utf-8"))
    f.save()
    return f


__all__: Iterable[str] = ("build_cut_svg", "generate_cut_path_file")
