# Generated by Django 4.2.30 on 2026-05-02 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="stripe payment intent id",
                    ),
                ),
                ("status", models.CharField(max_length=40, verbose_name="status")),
                ("amount_cents", models.PositiveIntegerField(verbose_name="amount (cents)")),
                (
                    "currency",
                    models.CharField(default="EUR", max_length=3, verbose_name="currency"),
                ),
                ("raw_event", models.JSONField(blank=True, default=dict, verbose_name="raw event")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_intents",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "payments_paymentintent",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "-created_at"], name="payments_pa_order_i_da7f86_idx"
                    )
                ],
            },
        ),
    ]
