# Generated by Django 4.2.30 on 2026-05-01 19:09

import apps.users.managers
from django.db import migrations, models
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("email", models.EmailField(db_index=True, max_length=254, verbose_name="email")),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=50, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=50, verbose_name="last name"),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, verbose_name="phone number"),
                ),
                (
                    "profile_picture",
                    models.TextField(
                        blank=True, max_length=100, null=True, verbose_name="profile picture"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ES", "Español"), ("EN", "English"), ("CA", "Català")],
                        default="ES",
                        max_length=2,
                        verbose_name="preferred language",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("shop_staff", "Shop Staff"),
                            ("customer", "Customer"),
                        ],
                        default="customer",
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="is active")),
                ("is_staff", models.BooleanField(default=False, verbose_name="is staff")),
                ("is_verified", models.BooleanField(default=False, verbose_name="email verified")),
                ("verification_token", models.CharField(blank=True, max_length=100)),
                ("verification_token_created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="updated at"),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("history_user_id", models.UUIDField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
            ],
            options={
                "verbose_name": "historical user",
                "verbose_name_plural": "historical users",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email")),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=50, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=50, verbose_name="last name"),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, verbose_name="phone number"),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pictures/",
                        verbose_name="profile picture",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ES", "Español"), ("EN", "English"), ("CA", "Català")],
                        default="ES",
                        max_length=2,
                        verbose_name="preferred language",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("shop_staff", "Shop Staff"),
                            ("customer", "Customer"),
                        ],
                        default="customer",
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="is active")),
                ("is_staff", models.BooleanField(default=False, verbose_name="is staff")),
                ("is_verified", models.BooleanField(default=False, verbose_name="email verified")),
                ("verification_token", models.CharField(blank=True, max_length=100)),
                ("verification_token_created_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users_user",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
                    models.Index(fields=["role", "is_active"], name="users_user_role_e1ec1a_idx"),
                ],
            },
            managers=[
                ("objects", apps.users.managers.UserManager()),
            ],
        ),
    ]
