# Generated by Django 4.2.30 on 2026-05-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="can_reserve_orders",
            field=models.BooleanField(default=False, verbose_name="can reserve orders"),
        ),
        migrations.AddField(
            model_name="user",
            name="can_reserve_orders",
            field=models.BooleanField(default=False, verbose_name="can reserve orders"),
        ),
    ]
